/**
 * Image generation domain models, shared across sim ↔ main ↔ renderer.
 *
 * A `PromptRequest` is produced by the sim and routed to the main-process
 * `ImageGenerationService`, which delegates to an `ImageProvider` (ComfyUI being
 * the first implementation). Generated bytes are cached on disk by
 * `AvatarService` / `BackgroundService` and their URLs pushed to the renderer as
 * `AvatarGeneratedEvent` / `BackgroundGeneratedEvent`.
 */

/** Total-pixel clamps for computed generation resolutions. */
export const MIN_PIXELS = 262_144 // 512×512
export const MAX_PIXELS = 2_097_152 // ~2 MP

/** Default ComfyUI server URL used before the user configures one. */
export const DEFAULT_COMFY_URL = 'http://localhost:8000'

/** Duration (ms) of the chat-page fade-to-black / fade-out when the background is
 *  regenerated on a scene change. Shared so the main-side wait and the renderer
 *  CSS transition stay in lockstep. */
export const BACKGROUND_TRANSITION_FADE_MS = 500

/** A request to generate one image, emitted by the sim. */
export interface PromptRequest {
  type: 'avatar' | 'background'
  /** `characterId` of the owning character (avatars). Omitted for backgrounds. */
  characterId?: string
  positive: string
  negative: string
  aspectRatio: {
    width: number
    height: number
  }
}

/** A generated avatar, pushed main → renderer. `url` is a renderer-loadable
 *  `genimg://` URL for the displayed (possibly transparency-edited) image, and
 *  `characterId` identifies which character it belongs to (for per-character
 *  demux on the chat page). `useFade` asks the chat page to animate the avatar
 *  in (the NPC moved) vs. show it instantly (the player moved, handled under the
 *  scene-change fade-to-black). */
export interface AvatarGeneratedEvent {
  characterId: string
  url: string
  useFade: boolean
}

/** An avatar removed (NPC deactivated), pushed main → renderer. `useFade` asks
 *  the chat page to fade the avatar out (the NPC moved) vs. remove it instantly
 *  (the player moved). */
export interface AvatarRemovedEvent {
  characterId: string
  useFade: boolean
}

/** A generated background, pushed main → renderer. `url` is a renderer-loadable
 *  `genimg://` URL. */
export interface BackgroundGeneratedEvent {
  url: string
}

/** Master on/off switch for image generation, plus avatar transparency
 *  post-processing options (persisted on disk). */
export interface ImgGenSettings {
  enabled: boolean
  /** Apply chroma-key transparency post-processing to generated avatars. */
  transparencyEnabled: boolean
  /** Appended to the positive prompt when transparency is enabled. */
  transparencyPositivePrompt: string
  /** Appended to the negative prompt when transparency is enabled. */
  transparencyNegativePrompt: string
  /** Chroma-key background color, hex (e.g. '#FF00FF'). */
  transparencyBackgroundColor: string
  /** Max Manhattan RGB distance treated as background. Range 0–765. */
  transparencySimilarity: number
  /** Edge feathering, 0.0 (sharp) – 1.0 (very soft). */
  transparencyEdgeSoftness: number
  /** Apply a Gaussian blur post-process to the generated background. */
  blurBackground: boolean
  /** Gaussian blur strength (sharp sigma). Range ~1–100. */
  blurAmount: number
  /** Delete generated character images from disk when the app quits. */
  deleteCharacterGenerationsOnQuit: boolean
}

/** ComfyUI settings shared across all workflows. */
export interface ComfyGenericSettings {
  url: string
  /** Total pixels targeted for `avatar` generations. */
  avatarTargetPixels: number
  /** Total pixels targeted for `background` generations. */
  backgroundTargetPixels: number
  /** Integer seed; -1 means a random seed per generation. */
  seed: number
  /** Whether to surface socket previews, or wait for the final image only. */
  usePreviews: boolean
  /** File name (key into `workflows.json`) of the active workflow. */
  selectedWorkflow: string
}

/**
 * JSONPaths into a workflow JSON identifying where each generation value is
 * written before submission. Validated against the workflow when saved.
 */
export interface WorkflowVariableBindings {//todo rename this
  /** Prepended to this workflow's positive prompt on every generation. */
  positivePromptOverride: string
  /** Prepended to this workflow's negative prompt on every generation. */
  negativePromptOverride: string
  positivePromptPath: string
  negativePromptPath: string
  widthPath: string
  heightPath: string
  seedPath: string
}

/** A selectable leaf in a workflow, for the binding dropdowns. */
export interface WorkflowLeafOption {
  /** Bracketed JSONPath, e.g. `$['31']['inputs']['seed']`. */
  path: string
  /** Display label: `<path> (Default <value preview>)`. */
  label: string
}
